### ISSUE TITLE
Union polygons

### ISSUE THREAD

**Issue by adnanefouam** [dartclub/turf_dart#1]
hello, thanks for bringing turf to dart !
is there will be  Union function that Takes two or more polygons and returns a combined polygon ?

**Comment by lukas-h** [comment]
This library is work in progress. Feel free to make a pull request, since it is not yet implemented.

**Comment by mohammedX6** [comment]
I have ported a libary that capable of doing all polygon Boolean operations on polygons (union, intersection, difference, xor) ( [More info here](https://pub.dev/packages/poly_bool_dart)

**Comment by lukas-h** [comment]
Hi @mohammedX6, this is really great! 😄 
Do you want to create a pull request to make this part of turf_dart?

**Comment by mohammedX6** [comment]
I don't think i have time to make pull requests but you can you use the libary dierftly without need of dart turf

**Comment by lukas-h** [comment]
closed because this is mostly implemented with the boolean* functions

**Comment by lukas-h** [comment]
what I wrote was not entirely correct. I did some test implementations of the `difference` function that is using @mohammedX6's `poly_bool_dart` lib.
I don't like that we have to convert between our turf's Polygon and poly_bool's Polygon classes.

@mohammedX6 do you think we can use your library as a blueprint to implement the functionality as part of turf_dart without a dependency to your library?

I created a new issue for that: https://github.com/dartclub/turf_dart/issues/166

CC @jsiedentop
