### ISSUE TITLE
CD to pub.dev for releases branch

### ISSUE THREAD

**Issue by lukas-h** [dartclub/turf_dart#10]
I want to setup a github action that automatically builds and deploys to [pub.dev](https://pub.dev) from the `releases` branch.

**Comment by baparham** [comment]
random resource link: https://dart.dev/tools/pub/publishing

@lukas-h I presume you are the first and only uploader also

**Comment by lukas-h** [comment]
Hi @baparham,
new workflow for publishing new versions is as follows:
- create a PR to the new `releases` branch, which triggers a GitHub Action that runs [`dart pub publish --dry-run`](https://dart.dev/tools/pub/publishing#performing-a-dry-run)
- once the PR is approved, another GitHub Action will publish the new version with `dart pub publish`

CC @tobrun
