### ISSUE TITLE
implement a getGeom() in invariants and refactor Boolean functions

### ISSUE THREAD

**Issue by armantorkzaban** [dartclub/turf_dart#105]
The point is to get the GeometryType out of a GeoJSONObject which can be either Feature or GeometryType. 
This happens in various boolean functions.

**Comment by lukas-h** [comment]
how should this function behave with `GeometryObject`, which can be a `GeometryCollection` or a concrete geometry type?

**Comment by lukas-h** [comment]
This is incomplete. No return type specified, cases like FeatureCollection are not handled. Otherwise okay.

**Comment by lukas-h** [comment]
decided against implementation.
