### ISSUE TITLE
invariant.dart getCoords return type

### ISSUE THREAD

**Issue by armantorkzaban** [dartclub/turf_dart#108]
It now returns a List, without checking the types of the contents, which should be Position.
@lukas-h, what do you think?

**Comment by lukas-h** [comment]
This line, right:

**Comment by lukas-h** [comment]
Maybe we should check for `List<CoordinateType>`, but there might be some other reason, why we implemented it that way.

**Comment by armantorkzaban** [comment]
It is about coordinates, in other words we are dealing with Positions. I do not see any reference to or need for BBox, therefore I would suggest we return a list of positions in that case.

**Comment by lukas-h** [comment]
Ok then, go ahead

**Comment by lukas-h** [comment]
We decided to leave it as it is, because we don't want to have too strict type checking for cases like nested lists of `Position`.
