### ISSUE TITLE
Match booleanEqual's parameters to that of turf_equality 

### ISSUE THREAD

**Issue by armantorkzaban** [dartclub/turf_dart#117]
the function uses the Equality in its core, but does not pass the adequate arguments into the class. This results in limited tests for equality, in cases where 'shifting positions' or 'reverse direction' has to be taken into account for the two objects being compared. 
What do you think @lukas-h

**Comment by lukas-h** [comment]
I agree, that we should adjust the interface of booleanEquals to the turf_equality interface.

But an overarching topic is:
I'm generally unsure what would be the right strategy to combine turf_equality (geojson-equality port), the booleanEquals, **and** on the other #45

**Comment by armantorkzaban** [comment]
https://github.com/dartclub/turf_dart/pull/91/commits/5c863e05f5882b040bd4001a83cd096c7a3bacee
