### ISSUE TITLE
Removing booleanEqual altogether?

### ISSUE THREAD

**Issue by armantorkzaban** [dartclub/turf_dart#118]
Now that we have geojson_equality, do we still need the booleanEqual package?

What do you think @lukas-h

**Comment by lukas-h** [comment]
I think we should keep it, but this is a much bigger discussion, involving #45 (Override of ==) as well.

Or my other comments here: https://github.com/dartclub/turf_dart/issues/117#issuecomment-1178169646
and here: https://github.com/dartclub/turf_dart/issues/45#issuecomment-1167109338

**Comment by lukas-h** [comment]
discussion continues in #45
