### ISSUE TITLE
booleanValid

### ISSUE THREAD

**Issue by armantorkzaban** [dartclub/turf_dart#129]
part of the validity of the data in the JSON is checked in the constructor of the different GeometryObjects. The problem is however that the assertion error trigger in debugging/development and not in production. However, during the dev/debug they trigger and mess with the tests. On the other hand some of the tests on the polygons are unknown to me and I will need to wrap my head around them. The mixture does not help. 
This issue is here for the conversation about the function.  @lukas-h, you may join the rescue effort any time. :-)

**Comment by armantorkzaban** [comment]
While the issue above is now solved (geojson test was checking all the test examples and would trigger error!) there is one single test that fails: './test/examples/booleans/valid/true/MultiPolygon/multipolygon-touch.geojson '
Since the function is supposed to "... check if the geometry is a valid according to the OGC Simple Feature Specification." according to [L10, turfJS/b-valid](https://github.com/Turfjs/turf/blob/2dd2ef88c44d847989fa0b82089f3f81fe433b83/packages/turf-boolean-valid/index.ts#L10) and the [standard](http://portal.opengeospatial.org/files/?artifact_id=829) states _"2. The Boundaries of any 2 Polygons that are elements of a MultiPolygon may not ‘cross’ and may touch at only a finite number of points. (Note that crossing is prevented by assertion 1 above).
∀ M ∈ MultiPolygon, ∀ Pi, Pj ∈ M.Geometries(), ∀ ci ∈ Pi.Boundaries(), cj ∈ Pj.Boundaries()
ci ∩ cj = {p1, ….., pk | pi ∈ Point, 1 <= i <= k}"_ 
and (multipolygon-touch.geojson)[https://github.com/Turfjs/turf/blob/master/packages/turf-boolean-valid/test/true/MultiPolygon/multipolygon-touch.geojson] touches apparently only in one point ('finite number of points), I conclude that we need to change the code to let this case pass. 
The issue is I do not know what _'finite'_ should mean. Can we call one point finite? @lukas-h

**Comment by armantorkzaban** [comment]
@lukas-h - what do you think about this proposal: [42 seconds ago](https://github.com/dartclub/turf_dart/commit/775f0eee9470364185ac8d224372699d08786d41)

**Comment by lukas-h** [comment]
booleanValid should not have any `assert`ions, and should be solely based on boolean conditions, and the function returning false/true

**Comment by lukas-h** [comment]
> The issue is I do not know what _'finite'_ should mean. Can we call one point finite? @lukas-h

Yes, let's do that.

And let's merge the feature now, with the warning, that is it not properly tested yet (early testing phase)
