### ISSUE TITLE
Could you export boolean_point_in_polygon function

### ISSUE THREAD

**Issue by favazHF** [dartclub/turf_dart#151]
We need to use this specific function but isn't export, please.

**Comment by lukas-h** [comment]
Hi @favazHF please create a pull request for that. It would be highly appreciated

**Comment by lukas-h** [comment]
@jsiedentop I think this is one of the implemented functions that is not exported yet?
https://github.com/dartclub/turf_dart/blob/main/lib/src/booleans/boolean_point_in_polygon.dart

**Comment by jsiedentop** [comment]
Exactly, so far none of the boolean functions have been exported at all. I have exported all boolean functions as part of booleanWithin #167 in `package:turf/boolean.dart`. But we need to take a closer look:

- `package:turf/turf.dart` should export all functionality, but a lot is missing (boolean functions among others)
- `package:turf/intersection.dart` is missing
- `package:turf/invariant.dart` is missing
- `package:turf/line_intersect.dart` is missing
- `package:turf/line_slice.dart` is defined as `library turf_along`. Seems to be an copy paste error.
- `package:turf/extensions.dart` and `package:turf/cluster.dart` are the only meta functionality directly exported.
- `package:turf/meta.dart` has all meta files except `extensions.dart`. Interesting, that meta also has `export 'src/line_segment.dart' hide lineSegment;`

Seems to have grown historically. Maybe we should take another look at it together?

**Comment by lukas-h** [comment]
closing this in favor of #169, which includes the requested improvement from this issue
