### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by baparham** [dartclub/turf_dart#18]
Early in the project, we still have a low hanging fruit opportunity to rename the `master` branch to `main`

Since there are only a few forks, it still seems like an easy endeavor but just will take some planned timing to make things run smoothly.

Basic implementation could just be as simple as following the web UI branch rename flow show here: https://github.com/github/renaming

and then perhaps setting `master` as a protected branch name also, so no accidental pushes to that branch occur in the future.

Any objections @lukas-h ?

P.S. If this is news to anybody, or want some backstory, here is the guidance from the software conservancy and a basic summary of the reason to change the branch name: https://sfconservancy.org/news/2020/jun/23/gitbranchname/

**Comment by lukas-h** [comment]
yes sure!
I have no outstanding changes to that branch, so let's do this!

**Comment by lukas-h** [comment]
Done
