### ISSUE TITLE
When will new release with line_slice included be released?

### ISSUE THREAD

**Issue by basvdijk** [dartclub/turf_dart#185]
For my project I need `line_slice` which is implemented in https://github.com/dartclub/turf_dart/blob/main/lib/src/line_slice.dart Any ideas when this will be released in a new turf_dart release on pub.dev?

**Comment by lukas-h** [comment]
Hi @basvdijk, our idea was to release a bigger 0.1.0 release. Instead I prepared a 0.0.10 release that contains `lineSlice` #186

**Comment by basvdijk** [comment]
@lukas-h thanks! Imho it is better to release often than to release big. This way every improvement is available to everyone instead of the ones who checkout master :)

**Comment by lukas-h** [comment]
Release will be done by today

**Comment by lukas-h** [comment]
The Github Action was stuck – only did a manual release today. Sorry.
