### ISSUE TITLE
Assemble multipoint from points

### ISSUE THREAD

**Issue by tobrun** [dartclub/turf_dart#19]
Refs: [geojson.dart#4](https://github.com/dartclub/turf_dart/blob/main/lib/src/geojson.dart#L4)

When browsing the source code, I was noticing a couple TODO. To make the work visible but to also inform users about potential missing feature gaps. It's better to also document them into an issue. This library supports an implementation of the [GeoJSON standard](https://tools.ietf.org/html/rfc7946) and to be fully compatible the code should allow create a [MultiPoint](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.3) object from a collection of [points](https://datatracker.ietf.org/doc/html/rfc7946#appendix-A.1).

**Comment by lukas-h** [comment]
@tobrun, thank you for filing the issues!
