### ISSUE TITLE
Midpoint test fails

### ISSUE THREAD

**Issue by baparham** [dartclub/turf_dart#3]
Running from the current `master` (80ce30b), on Windows, with dart version:
`Dart SDK version: 2.10.0-7.3.beta (beta) (Wed Aug 26 09:46:50 2020 +0200) on "windows_x64"`

Does this test pass for you folks? Perhaps on Linux or on another dart version?

Log output:
```
PS C:\git\turf_dart> dart test
Precompiling executable...
Precompiled test:test.
00:05 +1: test\components\midpoint_test.dart: midpoint
29.704243058393104
251.6519826898071
289.2560026566121, 326.5268244185807, 0
00:06 +9 -1: test\components\midpoint_test.dart: midpoint [E]
  Expected: <true>
    Actual: <false>

  package:test_api                         expect
  test\components\midpoint_test.dart 24:5  main.<fn>

00:06 +17 -1: Some tests failed.
```

Thanks!
I'll keep looking at it to see if I can find a bug in the implementation, or in the test.

**Comment by lukas-h** [comment]
midpoint tests work now, because I added the normalization of latitudes (antimeridian, meridian boundaries [180;-180])

see

`Position.toSigned()`
