### ISSUE TITLE
Add code coverage to PR test suite

### ISSUE THREAD

**Issue by baparham** [dartclub/turf_dart#35]
It would be nice to get insight into code coverage in PRs, especially at this early stage working on the lower level fundamentals of the library

**Comment by lukas-h** [comment]
I'll look for some solutions!

**Comment by baparham** [comment]
`dart test --coverage=coverage` writes the JSONs for coverage out do a directory, but doesn't report anything, so another step using something similar to `instanbul` or other coverage report generator would be needed. I'm surprised dart doesn't have an out of the box simple coverage reporter built in to at least just print some of the json values.

**Comment by baparham** [comment]
https://pub.dev/packages/coverage looks promising

**Comment by baparham** [comment]
seems most tools just say use `lcov` to format to html, which should be installed in our CI environment, but not necessarily locally, but that's probably OK. I'll experiment with a PR and see what it does.

**Comment by baparham** [comment]
...or did you want to take this @lukas-h ? I see you've assigned your self so I don't want to step on toes :-)

**Comment by lukas-h** [comment]
You can do it if you want 😉
