### ISSUE TITLE
geomEach: Better handling of nullable fields properties and geometry 

### ISSUE THREAD

**Issue by lukas-h** [dartclub/turf_dart#36]
https://github.com/dartclub/turf_dart/blob/6494415188765c42f434dd01b7fb88c28222cdd0/lib/src/meta.dart#L61

- Let's make the properties parameter of the `_forEachGeomInGeometryObject` function nullable.
- As for the `feature.geometry`, which can be null according to ([3.2](https://datatracker.ietf.org/doc/html/rfc7946#section-3.2)), I would propose, that these features should just be skipped.

```
A Feature object has a member with the name "geometry".  The value
 of the geometry member SHALL be either a Geometry object as
 defined above or, in the case that the Feature is unlocated, a
 JSON null value.
```

**Comment by lukas-h** [comment]
> * would propose, that these features should just be skipped.

Or as @tobrun implemented it: with nullable parameter sin the callback

**Comment by tobrun** [comment]
> Or as @tobrun implemented it: with nullable parameters in the callback

also fine with skipping, will defer that decision to y'all.

**Comment by lukas-h** [comment]
I would prefer the nullable parameters, @baparham what do you think?

**Comment by baparham** [comment]
I can imagine using this library and if I pass in a collection, and try to debug why some elements are skipped, I think that would be challenging. Getting null back in my callback completely removes that scenario from happening in the first place, since the typing for the callback will immediately indicate the expected behavior.

I vote nullable callback parameters.

**Comment by lukas-h** [comment]
> and try to debug why some elements are skipped

Yes, exactly. Sometimes it can even be intentional that e.g. the `geometry` is `null` in  feature.

---

seems like nullable callback parameters have won 🎉
