### ISSUE TITLE
Code coverage fails

### ISSUE THREAD

**Issue by lukas-h** [dartclub/turf_dart#39]

**Comment by baparham** [comment]
unfortunate, setting the Comment On PR step in the job to `continue-on-error` doesn't let the whole job pass.

I am reading up on whether there is a way to only run that step if the run is not from a fork

**Comment by baparham** [comment]
I thought 3a21086f9 would fix it, but it did not :-(

**Comment by lukas-h** [comment]
GH Actions are hard to debug
