### ISSUE TITLE
Add foreign members to each GeoJSON type

### ISSUE THREAD

**Issue by lukas-h** [dartclub/turf_dart#44]
https://github.com/dartclub/turf_dart/blob/bb33084f010b1676f3e88eb5342d86f925f66b61/lib/src/geojson.dart#L466

- [ ] fields
- [ ] id

---

- [ ] Point
- [ ] MultiPoint
- [ ] LineString
- [ ] MultiLineString
- [ ] Polygon
- [ ] MultiPolygon
- [ ] GeometryCollection
- [x] Feature
- [ ] FeatureCollection

**Comment by jsiedentop** [comment]
I'm closing this here, as this will be followed up in https://github.com/dartclub/geotypes/issues/4
