### ISSUE TITLE
README: getting started guide that showcases how to setup the dependency in your project and potentially an inline example

### ISSUE THREAD

**Issue by lukas-h** [dartclub/turf_dart#77]

**Comment by armantorkzaban** [comment]
Incl. composing some features + using some of the features

**Comment by lukas-h** [comment]
> Incl. composing some features + using some of the features

Do you mean how to use the constructors in geojson.dart?

**Comment by armantorkzaban** [comment]
No. These are the key points of our conversation re. this issue, transcribed here.
