### ISSUE TITLE
How to calculate the polygon area

### ISSUE THREAD

**Issue by yinxh2016** [dartclub/turf_dart#90]
The distance can be obtained from latlong2，but how to calculate the polygon area?

**Comment by lukas-h** [comment]
Hi, this package is still WIP, polygon area is not yet implemented here.
If you want to help us with the library, you could port the functionality from Turf.js https://github.com/Turfjs/turf/blob/master/packages/turf-area/index.ts

And take a look at our contributors guide

https://github.com/dartclub/turf_dart/blob/main/CONTRIBUTING.md

**Comment by lukas-h** [comment]
scheduled for implementation #136, closed therefore
