### ISSUE TITLE
[blocking] Port sweepline-intersections package

### ISSUE THREAD

**Issue by armantorkzaban** [dartclub/turf_dart#94]
https://github.com/rowanwins/sweepline-intersections

needed in line_intersect.dart> booleanDisjoint>booleanIntersects...

**Comment by lukas-h** [comment]
as I see, this should be the only dependency left for #88

**Comment by armantorkzaban** [comment]
While the sweepline is done to a great extent(benchmark and a test case remain), this is not the last dependencies. 
[geojson-rbush](https://github.com/DenisCarriere/geojson-rbush) is what we have forgotten to list in the blocking libraries! Tragic saga continues.

**Comment by lukas-h** [comment]
great success ~ Borat
