### ISSUE TITLE
[blocking] Port bbox-polygon package

### ISSUE THREAD

**Issue by armantorkzaban** [dartclub/turf_dart#97]
blocked center.dart's test

- [x] port from https://github.com/Turfjs/turf/tree/master/packages/turf-bbox-polygon
- [x] write documentation
- [x] write test
- [x] update readme

**Comment by lukas-h** [comment]
With what is this associated? #96? or with #91?

**Comment by lukas-h** [comment]
and what does center.dart have to do with it?

**Comment by armantorkzaban** [comment]
#96 ports 'center', center's test uses bbox-polyline (implemented here: #98)

**Comment by lukas-h** [comment]
We could go into the branch of #96 and just implement it there, if they all are interdependent!

**Comment by armantorkzaban** [comment]
That's also an approach. I thought it might get bigger of a task and get out of hand if we included this.

**Comment by lukas-h** [comment]
> I thought it might get bigger of a task and get out of hand if we included this.

I think it‘s okay, because we are already shortly before merging, it‘s only about two interdependent unit tests
